spring.datasource.url=jdbc:oracle:thin:@fatdatabase_high?TNS_ADMIN=/Users/ivmg5/Projects/oci-react-java-toodo/MtdrSpring/backend/src/main/resources/wallet/Wallet_FATDATABASE
spring.datasource.username=ADMIN
spring.datasource.password=SecurePass2025Xy
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.type=oracle.ucp.jdbc.PoolDataSource
spring.datasource.oracleucp.connection-factory-class-name=oracle.jdbc.pool.OracleDataSource
spring.datasource.oracleucp.sql-for-validate-connection=select * from dual
spring.datasource.oracleucp.connection-pool-name=connectionPoolName1
spring.datasource.oracleucp.initial-pool-size=15
spring.datasource.oracleucp.min-pool-size=10
spring.datasource.oracleucp.max-pool-size=30
logging.level.root=trace
logging.file.name=logs.log
logging.level.oracle.ucp=trace
telegram.bot.token=7923697191:AAH-IJvmJHKPKh9GvsKvVhtNNLJI_-X8lnY
telegram.bot.name=casrr_oracle_test_bot
spring.mvc.pathmatch.matching-strategy=ant-path-matcher

